backend:
  name: github
  repo: BrunoPirard/grapejs.local

media_folder: "public/assets/images/uploads"
public_folder: "public/assets/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    fields:
      - { label: "Pages Title", name: "title", widget: "string" }
      - { label: "Pages Type", name: "type", widget: "string" }
      - { label: "Pages Description", name: "description", widget: "markdown" }
      - { label: "Pages Date", name: "date", widget: "datetime" }

  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Posts Title", name: "title", widget: "string" }
      - { label: "Posts Type", name: "type", widget: "string" }
      - { label: "Posts Description", name: "description", widget: "markdown" }
      - { label: "Posts Date", name: "date", widget: "datetime" }
      - { label: "Posts Featured", name: "featuredImage", widget: "image" }
