backend:
  name: github
  repo: BrunoPirard/grapejs.local

media_folder: "public/img"
# public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Posts Title", name: "title", widget: "string" }
      - { label: "Posts Type", name: "type", widget: "string" }
      - { label: "Posts Description", name: "description", widget: "string" }
      - { label: "Posts Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["posts"] }

  # Our pages e.g. About
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["pages"] }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
